exports.ResponseMessage = {
  email_already_associate_with_another_account:
    "Email already associated with another account",
  mobile_number_already_associate_with_another_account:
    "Mobile number already associated with another account",
  You_ve_reached_the_maximum_OTP_check_attempts_please_try_after_some_time:
    "You've reached the maximum OTP check attempts, Please try after some time",
  You_ve_reached_the_maximum_OTP_send_attempts_please_try_after_some_time:
    "You've reached the maximum OTP send attempts, Please try after some time",
  mobile_number_is_already_registered: "Mobile number is already registered",
  mobile_number_is_already_registered_please_try_with_another:
    "Mobile number is already registered, please try with another",
  internal_server_error: "Internal server error",
  suggested_tasks_fetched_successfully: "Suggested tasks fetched successfully.",
  invalid_google_token: "Invalid google token",
  password_not_matched: "Password not matched",
  email_id_is_not_exist: "Email Id Is Not Exist..",
  suggested_task_already_added: "Task already added",
  otp_sent_successfully: "OTP sent successfully",
  otp_not_matched: "OTP not matched",
  gender_updated_successfully: "Gender updated successfully",
  user_register_successfully: "User register successfully",
  otp_verified_successfully: "OTP verified successfully",
  user_deleted_successfully: "User deleted successfully.",
  login_successfully: "Login successfully",
  get_login_user_info_successfully: "Get login user info successfully",
  password_changed_successfully: "Password changed successfully",
  password_must_be_at_least_6_characters:
    "password_must_be_at_least_6_characters",
  password_not_changed: "Password not changed",
  forgot_password_link_sent_on_your_email:
    "Forgot password link sent on your email",
  user_updated_successfully: "User updated successfully",
  invalid_credentials: "Invalid credentials",
  email_or_otp_number_is_required: "Email or Otp is required",
  user_not_found: "User not found",
  please_try_to_correct_credentials: "Please try to correct credentials",
  task_added_successfully: "Task added successfully",
  task_added_as_suggested_successfully: "Task added as suggested successfully",
  task_get_successfully: "Task get successfully",
  task_report_get_successfully: "Task report get successfully",
  get_total_task_report_successfully: "Get total task report successfully",
  combined_year_wise_task_report_generated_successfully: "Combined year-wise task report generated successfully.",
  please_provide_valid_task_ids: "Please provide valid task IDs.",
  get_task_week_wise_task_report_successfully:
    "Get task week wise task report successfully",
  task_not_found: "Task not found.",
  task_is_not_ongoing: "Task is not ongoing.",
  task_is_already_completed: "Task is already completed.",
  task_update_successfully: "Task update successfully.",
  get_selected_total_task_wise_report_successfully: "Get selected total task wise report successfully.",
  task_wise_check_in_report_generated_successfully: "Task-wise check-in report generated successfully.",
  get_task_month_wise_report_successfully: "Get task month wise report successfully.",
  get_task_year_wise_report_successfully: "Get task year wise report successfully.",
  task_delete_successfully: "Task delete successfully.",
  failed_to_delete_the_task: "Failed to delete the task.",
  task_completed_successfully: "Task marked as completed successfully.",
  task_canceled_successfully: "Task marked as canceled successfully.",
  task_status_count_fetched_successfully: "Task status count fetched successfully.",
  task_reinstated_successfully: "Task reinstated successfully.",
  task_is_not_canceled: "Task is not canceled.",
  period_added_successfully: "Period added successfully",
  get_period_successfully: "Get Periods successfully",
  dnd_status_updated_successfully: "DND status updated successfully",
  logout_successfully: "Logout successfully",
  token_is_invalid_please_log_in_again: "Token is invalid please log in again",
};
